use crate::{
    AuthorityBinding, FenceToken, LeaseError, LeaseRecord, LeaseRegistry, LeaseState,
    ReservationError, ReservationRecord, ReservationRegistry, ReservationState, ReservedResource,
};
use ptah_identifiers::{ConnectionEpoch, EntityId, EntityRef, NodeGeneration, NodeId};
use ptah_ledger::{CanonicalRecord, Ledger};
use ptah_node_agent::{NodeResourceSnapshot, ResourceUnit};
use ptah_node_link::SessionBinding;
use rusqlite::{Connection, OpenFlags, params};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    collections::{HashMap, HashSet},
    path::{Path, PathBuf},
};
use thiserror::Error;

const JOURNAL_KIND: &str = "runtime.e02-authority-journal";
const ENVELOPE_SCHEMA: &str = "urn:ptah:schema:common:entity-envelope:0.1.0";
const VERSION: &str = "0.1.0";
const EXTENSION_KEY: &str = "ptah.e02_authority_recovery";

type ReservationMap = HashMap<EntityId, StoredReservation>;
type LeaseMap = HashMap<EntityId, StoredLease>;

/// Durable E02 recovery failure. Recovery is fail-closed: no partially rebuilt
/// authority is ever returned.
#[derive(Debug, Error)]
pub enum RecoveryError {
    /// A03 rejected the durable store or canonical document.
    #[error("A03 ledger rejected E02 durable authority: {0}")]
    Ledger(String),
    /// A03 canonical-row traversal failed.
    #[error("A03 durable authority read failed: {0}")]
    Sqlite(#[from] rusqlite::Error),
    /// Persisted JSON is malformed.
    #[error("E02 durable authority JSON is invalid: {0}")]
    Json(#[from] serde_json::Error),
    /// Persisted state is internally inconsistent or ambiguous.
    #[error("E02 durable authority is corrupt or ambiguous: {0}")]
    Corrupt(String),
    /// Current-session recovery cites another A02 resource snapshot.
    #[error("recovered Reservation cites stale resource evidence")]
    StaleResourceEvidence,
    /// Reservation replay failed mechanical admission.
    #[error("recovered Reservation is inadmissible: {0}")]
    Reservation(#[from] ReservationError),
    /// Lease replay failed mechanical admission.
    #[error("recovered Lease is inadmissible: {0}")]
    Lease(#[from] LeaseError),
    /// Durable Fence history did not replay monotonically.
    #[error("recovered Fence mismatch: persisted {persisted}, reconstructed {reconstructed}")]
    FenceMismatch {
        /// Durable Fence.
        persisted: u64,
        /// Fence generated by deterministic replay.
        reconstructed: u64,
    },
}

/// Current-session authority rebuilt from durable truth.
pub struct RecoveredAuthority {
    reservations: ReservationRegistry,
    leases: LeaseRegistry,
}

impl RecoveredAuthority {
    /// Read recovered Reservation accounting.
    #[must_use]
    pub const fn reservations(&self) -> &ReservationRegistry {
        &self.reservations
    }

    /// Mutate Reservation accounting through normal E02 mechanics.
    #[must_use]
    pub fn reservations_mut(&mut self) -> &mut ReservationRegistry {
        &mut self.reservations
    }

    /// Read recovered Lease/Fence authority.
    #[must_use]
    pub const fn leases(&self) -> &LeaseRegistry {
        &self.leases
    }

    /// Mutate Lease/Fence authority through normal E02 mechanics.
    #[must_use]
    pub fn leases_mut(&mut self) -> &mut LeaseRegistry {
        &mut self.leases
    }
}

/// A03-backed append-only E02 recovery journal.
///
/// E02 owns no database schema. Every write is an A03 canonical
/// `common.entity-envelope` record and the recovery snapshot lives only in the
/// frozen envelope extension surface.
pub struct DurableAuthorityStore {
    path: PathBuf,
    ledger: Ledger,
}

impl DurableAuthorityStore {
    /// Open or create the underlying A03 ledger.
    ///
    /// # Errors
    /// Returns an error when A03 rejects storage, migration or canonical policy.
    pub fn open(path: impl AsRef<Path>) -> Result<Self, RecoveryError> {
        let path = path.as_ref().to_path_buf();
        let ledger = Ledger::open(&path).map_err(ledger_error)?;
        Ok(Self { path, ledger })
    }

    /// Append one immutable Reservation recovery snapshot.
    ///
    /// # Errors
    /// Fails closed if existing journal truth is malformed or A03 rejects append.
    pub fn persist_reservation(
        &mut self,
        record: &ReservationRecord,
    ) -> Result<(), RecoveryError> {
        let sequence = self.next_sequence()?;
        self.append(
            JournalEntry::Reservation {
                sequence,
                value: StoredReservation::from_record(record),
            },
            record.binding().attempt_ref(),
        )
    }

    /// Append one immutable Lease/Fence recovery snapshot.
    ///
    /// # Errors
    /// Fails closed if existing journal truth is malformed or A03 rejects append.
    pub fn persist_lease(&mut self, record: &LeaseRecord) -> Result<(), RecoveryError> {
        let sequence = self.next_sequence()?;
        self.append(
            JournalEntry::Lease {
                sequence,
                value: StoredLease::from_record(record),
            },
            record.binding().attempt_ref(),
        )
    }

    /// Reconstruct authority for one exact current E01 session/A02 snapshot.
    /// Old sessions contribute only permanent Fence history.
    ///
    /// # Errors
    /// Any malformed, ambiguous, stale-evidence or inadmissible state fails closed.
    pub fn recover(
        &self,
        session: &SessionBinding,
        snapshot: &NodeResourceSnapshot,
        now: u64,
    ) -> Result<RecoveredAuthority, RecoveryError> {
        let durable = latest(self.read_entries()?)?;
        validate_histories(&durable.reservations, &durable.leases)?;

        let mut replay = replay_reservations(session, snapshot, &durable.reservations)?;
        let mut leases = replay_leases(session, &replay.registry, &durable.leases)?;
        apply_lease_states(session, &mut leases, &durable.leases, now)?;
        apply_reservation_states(&mut replay.registry, &replay.current, now)?;
        revoke_leases_without_active_reservation(
            session,
            &replay.registry,
            &mut leases,
            &durable.leases,
        )?;

        Ok(RecoveredAuthority {
            reservations: replay.registry,
            leases,
        })
    }

    fn next_sequence(&self) -> Result<u64, RecoveryError> {
        self.read_entries()?
            .iter()
            .map(JournalEntry::sequence)
            .max()
            .unwrap_or(0)
            .checked_add(1)
            .ok_or_else(|| RecoveryError::Corrupt("journal sequence overflow".to_owned()))
    }

    fn append(
        &mut self,
        entry: JournalEntry,
        authority_ref: &EntityRef,
    ) -> Result<(), RecoveryError> {
        let journal_ref = EntityRef::new(JOURNAL_KIND)
            .map_err(|error| RecoveryError::Corrupt(error.to_string()))?;
        let document = json!({
            "entity_id": journal_ref.entity_id.to_string(),
            "entity_kind": JOURNAL_KIND,
            "schema_id": ENVELOPE_SCHEMA,
            "schema_version": VERSION,
            "record_revision": 1,
            "created_at": "2026-09-06T00:00:00Z",
            "updated_at": "2026-09-06T00:00:00Z",
            "global_scope": "ptah_global",
            "authority_ref": authority_ref,
            "privacy_class": "internal",
            "audience": "private_owner",
            "redaction_policy": "none",
            "retention_policy": {
                "policy_id": "ptah.e02.authority-recovery",
                "policy_version": VERSION,
                "retention_class": "operational"
            },
            "extensions": {
                EXTENSION_KEY: {
                    "schema_id": "urn:ptah:extension:e02-authority-recovery:0.1.0",
                    "schema_version": VERSION,
                    "value": serde_json::to_value(entry)?
                }
            }
        });
        let record = CanonicalRecord::from_document(document).map_err(ledger_error)?;
        let write = self.ledger.begin_write().map_err(ledger_error)?;
        write.insert(&record).map_err(ledger_error)?;
        write.commit().map_err(ledger_error)
    }

    fn read_entries(&self) -> Result<Vec<JournalEntry>, RecoveryError> {
        let connection = Connection::open_with_flags(&self.path, OpenFlags::SQLITE_OPEN_READ_ONLY)?;
        let mut statement = connection.prepare(
            "SELECT entity_id, entity_kind, schema_id, schema_version, record_revision, \
                    authority_ref_json, node_generation, document_json \
             FROM ptah_entity_records WHERE entity_kind = ?1 \
             ORDER BY entity_id, record_revision",
        )?;
        let rows = statement.query_map(params![JOURNAL_KIND], |row| {
            Ok(RowData {
                entity_id: row.get(0)?,
                entity_kind: row.get(1)?,
                schema_id: row.get(2)?,
                schema_version: row.get(3)?,
                revision: row.get(4)?,
                authority_json: row.get(5)?,
                node_generation: row.get(6)?,
                document_json: row.get(7)?,
            })
        })?;

        let mut result = Vec::new();
        let mut sequences = HashSet::new();
        for row in rows {
            let row = row?;
            let document: Value = serde_json::from_str(&row.document_json)?;
            let canonical = CanonicalRecord::from_document(document.clone()).map_err(ledger_error)?;
            validate_row(&row, &canonical)?;
            let authority: EntityRef = serde_json::from_str(&row.authority_json)?;
            let payload = document
                .get("extensions")
                .and_then(|extensions| extensions.get(EXTENSION_KEY))
                .and_then(|extension| extension.get("value"))
                .ok_or_else(|| RecoveryError::Corrupt("missing E02 journal extension".to_owned()))?;
            let entry: JournalEntry = serde_json::from_value(payload.clone())?;
            if entry.sequence() == 0 || !sequences.insert(entry.sequence()) {
                return Err(RecoveryError::Corrupt(format!(
                    "invalid or duplicate journal sequence {}",
                    entry.sequence()
                )));
            }
            if entry.attempt_ref() != &authority {
                return Err(RecoveryError::Corrupt(
                    "journal authority_ref differs from Attempt".to_owned(),
                ));
            }
            result.push(entry);
        }
        result.sort_by_key(JournalEntry::sequence);
        Ok(result)
    }
}

struct DurableState {
    reservations: ReservationMap,
    leases: LeaseMap,
}

struct ReservationReplay {
    registry: ReservationRegistry,
    current: Vec<StoredReservation>,
}

fn replay_reservations(
    session: &SessionBinding,
    snapshot: &NodeResourceSnapshot,
    reservations: &ReservationMap,
) -> Result<ReservationReplay, RecoveryError> {
    let mut registry = ReservationRegistry::new(session, snapshot)?;
    let mut current: Vec<_> = reservations
        .values()
        .filter(|value| value.matches(session))
        .cloned()
        .collect();
    current.sort_by_key(|value| (value.created_at, value.reservation_ref.entity_id.to_string()));

    for value in &current {
        if value.snapshot_ref != snapshot.snapshot_ref {
            return Err(RecoveryError::StaleResourceEvidence);
        }
        let resources = value
            .resources
            .iter()
            .map(StoredResource::runtime)
            .collect::<Result<Vec<_>, _>>()?;
        registry.reserve(
            value.reservation_ref.clone(),
            AuthorityBinding::new(
                value.attempt_ref.clone(),
                value.node_id,
                NodeGeneration::new(value.node_generation),
                ConnectionEpoch::new(value.connection_epoch),
            ),
            value.snapshot_ref.clone(),
            resources,
            value.created_at,
            value.expires_at,
        )?;
    }
    Ok(ReservationReplay { registry, current })
}

fn replay_leases(
    session: &SessionBinding,
    reservations: &ReservationRegistry,
    leases: &LeaseMap,
) -> Result<LeaseRegistry, RecoveryError> {
    let mut registry = LeaseRegistry::new();
    let mut by_attempt: HashMap<EntityRef, Vec<StoredLease>> = HashMap::new();
    let mut global_floor: HashMap<EntityRef, u64> = HashMap::new();

    for value in leases.values() {
        global_floor
            .entry(value.attempt_ref.clone())
            .and_modify(|floor| *floor = (*floor).max(value.fence))
            .or_insert(value.fence);
        if value.matches(session) {
            by_attempt
                .entry(value.attempt_ref.clone())
                .or_default()
                .push(value.clone());
        }
    }

    let mut attempts: Vec<_> = by_attempt.into_iter().collect();
    attempts.sort_by_key(|(attempt, _)| attempt.entity_id.to_string());
    for (attempt, mut attempt_leases) in attempts {
        replay_attempt_leases(&mut registry, reservations, &attempt, &mut attempt_leases)?;
    }
    for (attempt, floor) in global_floor {
        registry.recover_fence_floor(attempt, fence(floor)?);
    }
    Ok(registry)
}

fn replay_attempt_leases(
    registry: &mut LeaseRegistry,
    reservations: &ReservationRegistry,
    attempt: &EntityRef,
    attempt_leases: &mut [StoredLease],
) -> Result<(), RecoveryError> {
    attempt_leases.sort_by_key(|value| value.fence);
    if let Some(first) = attempt_leases.first()
        && first.fence > 1
    {
        registry.recover_fence_floor(attempt.clone(), fence(first.fence - 1)?);
    }
    for value in attempt_leases {
        let reservation = reservations
            .reservation(&value.reservation_ref)
            .ok_or_else(|| {
                RecoveryError::Corrupt(format!(
                    "Lease {} has no current-session Reservation",
                    value.lease_ref.entity_id
                ))
            })?
            .clone();
        let rebuilt = registry.issue(
            &reservation,
            value.lease_ref.clone(),
            value.issued_at,
            value.expires_at,
        )?;
        if rebuilt.fence().value() != value.fence {
            return Err(RecoveryError::FenceMismatch {
                persisted: value.fence,
                reconstructed: rebuilt.fence().value(),
            });
        }
    }
    Ok(())
}

fn apply_lease_states(
    session: &SessionBinding,
    registry: &mut LeaseRegistry,
    leases: &LeaseMap,
    now: u64,
) -> Result<(), RecoveryError> {
    for value in leases.values().filter(|value| value.matches(session)) {
        match value.state {
            StoredLeaseState::Active => {}
            StoredLeaseState::Revoked => {
                if registry.state(&value.lease_ref) == Some(LeaseState::Active) {
                    registry.revoke(&value.lease_ref)?;
                }
            }
            StoredLeaseState::Expired => {
                registry.expire(value.expires_at);
            }
            StoredLeaseState::Superseded => validate_superseded(registry, value)?,
        }
    }
    registry.expire(now);
    Ok(())
}

fn validate_superseded(registry: &LeaseRegistry, value: &StoredLease) -> Result<(), RecoveryError> {
    let superseded = registry.state(&value.lease_ref) == Some(LeaseState::Superseded)
        || registry
            .highest_fence(&value.attempt_ref)
            .is_some_and(|highest| highest.value() > value.fence);
    if superseded {
        Ok(())
    } else {
        Err(RecoveryError::Corrupt(format!(
            "Lease {} claims superseded without newer Fence",
            value.lease_ref.entity_id
        )))
    }
}

fn apply_reservation_states(
    registry: &mut ReservationRegistry,
    current: &[StoredReservation],
    now: u64,
) -> Result<(), RecoveryError> {
    for value in current {
        match value.state {
            StoredReservationState::Active => {}
            StoredReservationState::Released => {
                registry.release(&value.reservation_ref, value.created_at)?;
            }
            StoredReservationState::Expired => {
                registry.expire(value.expires_at);
            }
            StoredReservationState::Revoked => {
                registry.revoke(&value.reservation_ref)?;
            }
        }
    }
    registry.expire(now);
    Ok(())
}

fn revoke_leases_without_active_reservation(
    session: &SessionBinding,
    reservations: &ReservationRegistry,
    leases: &mut LeaseRegistry,
    durable_leases: &LeaseMap,
) -> Result<(), RecoveryError> {
    for value in durable_leases.values().filter(|value| value.matches(session)) {
        let backing_inactive = reservations
            .reservation(&value.reservation_ref)
            .is_some_and(|reservation| reservation.state() != ReservationState::Active);
        if backing_inactive && leases.state(&value.lease_ref) == Some(LeaseState::Active) {
            leases.revoke(&value.lease_ref)?;
        }
    }
    Ok(())
}

#[derive(Debug)]
struct RowData {
    entity_id: String,
    entity_kind: String,
    schema_id: String,
    schema_version: String,
    revision: i64,
    authority_json: String,
    node_generation: Option<i64>,
    document_json: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "entry_kind", rename_all = "snake_case")]
enum JournalEntry {
    Reservation {
        sequence: u64,
        value: StoredReservation,
    },
    Lease {
        sequence: u64,
        value: StoredLease,
    },
}

impl JournalEntry {
    const fn sequence(&self) -> u64 {
        match self {
            Self::Reservation { sequence, .. } | Self::Lease { sequence, .. } => *sequence,
        }
    }

    const fn attempt_ref(&self) -> &EntityRef {
        match self {
            Self::Reservation { value, .. } => &value.attempt_ref,
            Self::Lease { value, .. } => &value.attempt_ref,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct StoredResource {
    key: String,
    unit: ResourceUnit,
    quantity: f64,
}

impl StoredResource {
    fn from_runtime(value: &ReservedResource) -> Self {
        Self {
            key: value.resource_key().to_owned(),
            unit: value.unit(),
            quantity: value.quantity(),
        }
    }

    fn runtime(&self) -> Result<ReservedResource, RecoveryError> {
        ReservedResource::new(self.key.clone(), self.unit, self.quantity).map_err(RecoveryError::from)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum StoredReservationState {
    Active,
    Released,
    Expired,
    Revoked,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct StoredReservation {
    reservation_ref: EntityRef,
    attempt_ref: EntityRef,
    node_id: NodeId,
    node_generation: u64,
    connection_epoch: u64,
    snapshot_ref: EntityRef,
    resources: Vec<StoredResource>,
    created_at: u64,
    expires_at: u64,
    state: StoredReservationState,
}

impl StoredReservation {
    fn from_record(record: &ReservationRecord) -> Self {
        let state = match record.state() {
            ReservationState::Active => StoredReservationState::Active,
            ReservationState::Released => StoredReservationState::Released,
            ReservationState::Expired => StoredReservationState::Expired,
            ReservationState::Revoked => StoredReservationState::Revoked,
        };
        Self {
            reservation_ref: record.reservation_ref().clone(),
            attempt_ref: record.binding().attempt_ref().clone(),
            node_id: record.binding().node_id(),
            node_generation: record.binding().node_generation().value(),
            connection_epoch: record.binding().connection_epoch().value(),
            snapshot_ref: record.resource_snapshot_ref().clone(),
            resources: record
                .resources()
                .iter()
                .map(StoredResource::from_runtime)
                .collect(),
            created_at: record.created_at_unix_seconds(),
            expires_at: record.expires_at_unix_seconds(),
            state,
        }
    }

    fn matches(&self, session: &SessionBinding) -> bool {
        self.node_id == session.node_id
            && self.node_generation == session.node_generation.value()
            && self.connection_epoch == session.connection_epoch.value()
    }

    fn same_immutable(&self, other: &Self) -> bool {
        self.reservation_ref == other.reservation_ref
            && self.attempt_ref == other.attempt_ref
            && self.node_id == other.node_id
            && self.node_generation == other.node_generation
            && self.connection_epoch == other.connection_epoch
            && self.snapshot_ref == other.snapshot_ref
            && self.resources == other.resources
            && self.created_at == other.created_at
            && self.expires_at == other.expires_at
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum StoredLeaseState {
    Active,
    Expired,
    Revoked,
    Superseded,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct StoredLease {
    lease_ref: EntityRef,
    reservation_ref: EntityRef,
    attempt_ref: EntityRef,
    node_id: NodeId,
    node_generation: u64,
    connection_epoch: u64,
    fence: u64,
    issued_at: u64,
    expires_at: u64,
    state: StoredLeaseState,
}

impl StoredLease {
    fn from_record(record: &LeaseRecord) -> Self {
        let state = match record.state() {
            LeaseState::Active => StoredLeaseState::Active,
            LeaseState::Expired => StoredLeaseState::Expired,
            LeaseState::Revoked => StoredLeaseState::Revoked,
            LeaseState::Superseded => StoredLeaseState::Superseded,
        };
        Self {
            lease_ref: record.lease_ref().clone(),
            reservation_ref: record.reservation_ref().clone(),
            attempt_ref: record.binding().attempt_ref().clone(),
            node_id: record.binding().node_id(),
            node_generation: record.binding().node_generation().value(),
            connection_epoch: record.binding().connection_epoch().value(),
            fence: record.fence().value(),
            issued_at: record.issued_at_unix_seconds(),
            expires_at: record.expires_at_unix_seconds(),
            state,
        }
    }

    fn matches(&self, session: &SessionBinding) -> bool {
        self.node_id == session.node_id
            && self.node_generation == session.node_generation.value()
            && self.connection_epoch == session.connection_epoch.value()
    }

    fn same_immutable(&self, other: &Self) -> bool {
        self.lease_ref == other.lease_ref
            && self.reservation_ref == other.reservation_ref
            && self.attempt_ref == other.attempt_ref
            && self.node_id == other.node_id
            && self.node_generation == other.node_generation
            && self.connection_epoch == other.connection_epoch
            && self.fence == other.fence
            && self.issued_at == other.issued_at
            && self.expires_at == other.expires_at
    }
}

fn latest(entries: Vec<JournalEntry>) -> Result<DurableState, RecoveryError> {
    let mut reservations: ReservationMap = HashMap::new();
    let mut leases: LeaseMap = HashMap::new();
    for entry in entries {
        match entry {
            JournalEntry::Reservation { value, .. } => {
                let key = value.reservation_ref.entity_id;
                if let Some(previous) = reservations.get(&key)
                    && !previous.same_immutable(&value)
                {
                    return Err(RecoveryError::Corrupt(format!(
                        "Reservation {key} changed immutable authority"
                    )));
                }
                validate_reservation(&value)?;
                reservations.insert(key, value);
            }
            JournalEntry::Lease { value, .. } => {
                let key = value.lease_ref.entity_id;
                if let Some(previous) = leases.get(&key)
                    && !previous.same_immutable(&value)
                {
                    return Err(RecoveryError::Corrupt(format!(
                        "Lease {key} changed immutable authority"
                    )));
                }
                validate_lease(&value)?;
                leases.insert(key, value);
            }
        }
    }
    Ok(DurableState {
        reservations,
        leases,
    })
}

fn validate_histories(
    reservations: &ReservationMap,
    leases: &LeaseMap,
) -> Result<(), RecoveryError> {
    let mut fences: HashMap<EntityRef, HashSet<u64>> = HashMap::new();
    for lease in leases.values() {
        let reservation = reservations
            .get(&lease.reservation_ref.entity_id)
            .ok_or_else(|| {
                RecoveryError::Corrupt(format!(
                    "Lease {} references unknown Reservation {}",
                    lease.lease_ref.entity_id, lease.reservation_ref.entity_id
                ))
            })?;
        if reservation.attempt_ref != lease.attempt_ref
            || reservation.node_id != lease.node_id
            || reservation.node_generation != lease.node_generation
            || reservation.connection_epoch != lease.connection_epoch
        {
            return Err(RecoveryError::Corrupt(format!(
                "Lease {} disagrees with Reservation binding",
                lease.lease_ref.entity_id
            )));
        }
        if !fences
            .entry(lease.attempt_ref.clone())
            .or_default()
            .insert(lease.fence)
        {
            return Err(RecoveryError::Corrupt(format!(
                "Attempt {} has duplicate Fence {}",
                lease.attempt_ref.entity_id, lease.fence
            )));
        }
    }
    Ok(())
}

fn validate_reservation(value: &StoredReservation) -> Result<(), RecoveryError> {
    if value.resources.is_empty()
        || value.expires_at <= value.created_at
        || value.resources.iter().any(|resource| {
            resource.key.is_empty() || !resource.quantity.is_finite() || resource.quantity <= 0.0
        })
    {
        return Err(RecoveryError::Corrupt(format!(
            "Reservation {} has invalid durable fields",
            value.reservation_ref.entity_id
        )));
    }
    Ok(())
}

fn validate_lease(value: &StoredLease) -> Result<(), RecoveryError> {
    if value.fence == 0 || value.expires_at <= value.issued_at {
        return Err(RecoveryError::Corrupt(format!(
            "Lease {} has invalid durable fields",
            value.lease_ref.entity_id
        )));
    }
    Ok(())
}

fn validate_row(row: &RowData, record: &CanonicalRecord) -> Result<(), RecoveryError> {
    let revision = u64::try_from(row.revision)
        .map_err(|_| RecoveryError::Corrupt("negative journal revision".to_owned()))?;
    if row.entity_id != record.entity_id().to_string()
        || row.entity_kind != record.entity_kind().as_str()
        || row.schema_id != record.schema_id()
        || row.schema_version != record.schema_version()
        || revision != record.record_revision().value()
        || row.node_generation.is_some()
        || row.entity_kind != JOURNAL_KIND
        || row.schema_id != ENVELOPE_SCHEMA
        || row.schema_version != VERSION
        || revision != 1
    {
        return Err(RecoveryError::Corrupt(
            "A03 row indexes disagree with canonical journal document".to_owned(),
        ));
    }
    Ok(())
}

fn fence(value: u64) -> Result<FenceToken, RecoveryError> {
    FenceToken::new(value).map_err(|error| RecoveryError::Corrupt(error.to_string()))
}

fn ledger_error(error: impl std::fmt::Display) -> RecoveryError {
    RecoveryError::Ledger(error.to_string())
}
