import assert from "node:assert/strict";
import test from "node:test";
import { BrowserProviderError, ProviderCore, isDefaultPersonalProfilePath, redactEvidence, redactUrl } from "../src/index.mjs";

class FakeBackend {
  constructor() { this.closed = 0; this.events = []; }
  describe() { return { implementation: "fake" }; }
  async launchProcess() { return { aliases: [{ kind: "pid", value: "1234" }] }; }
  async createContext() { return { aliases: [{ kind: "context", value: "ctx-1" }] }; }
  async verifyContext() { return { verified: true, evidence: { completeness: "verified" } }; }
  async verifyProcess() { return { verified: true, evidence: { liveness: "verified" } }; }
  async createPage() { return { aliases: [{ kind: "target", value: "page-1" }] }; }
  async navigate(_page, { url }) { return { state: "committed", committedUrl: url, status: 200, evidence: { headers: { authorization: "secret", accept: "text/html" } } }; }
  async verifyPageState() { return { verified: true, state: "load_complete", url: "https://example.test/", title: "Example" }; }
  async captureEvidence() { return { capturedAt: "2026-08-20T00:00:00Z", mediaType: "application/json", bytes: Buffer.from("{}"), metadata: { headers: { cookie: "secret", accept: "application/json" } } }; }
  async uploadFiles() { return { acknowledged: true }; }
  async readDownloadChunk(_handle, { offset, maxBytes }) { const all = Buffer.from("abcdef"); const end = Math.min(offset + maxBytes, all.length); return { bytes: all.subarray(offset, end), eof: end >= all.length }; }
  async pollEvents() { return this.events.splice(0); }
  async detachProcess() {}
  async closeProcess() { this.closed += 1; }
}
async function liveTree() {
  const backend = new FakeBackend(); const core = new ProviderCore({ backend, providerGeneration: 7, maxDownloadChunkBytes: 4 });
  const process = await core.launchProcess({ expectedProviderGeneration: 7, processGeneration: 11, profileMode: "ephemeral" });
  const context = await core.createContext({ expectedProviderGeneration: 7, processHandle: process.processHandle, processGeneration: 11, contextGeneration: 13, storageMode: "ephemeral" });
  const page = await core.createPage({ expectedProviderGeneration: 7, contextHandle: context.contextHandle, processGeneration: 11, contextGeneration: 13, pageGeneration: 17 });
  return { backend, core, process, context, page };
}
test("provider description refuses backend handles as canonical identity", () => { const d = new ProviderCore({ backend: new FakeBackend(), providerGeneration: 1 }).describe(); assert.equal(d.authority.backendHandlesAreAliases,true); assert.equal(d.authority.providerAckIsCompletion,false); assert.equal(d.authority.browserOwnsContentIdentity,false); assert.equal(d.authority.challengeBypassAuthorized,false); });
test("persistent writable profile requires lease and fence authority", async () => { const core=new ProviderCore({backend:new FakeBackend(),providerGeneration:1}); await assert.rejects(core.launchProcess({expectedProviderGeneration:1,processGeneration:1,profileMode:"persistent_exclusive",userDataDir:"/safe/isolated-profile"}), e=>e instanceof BrowserProviderError&&e.code==="writable_profile_authority_required"); });
test("ordinary personal browser profiles are rejected", async () => { assert.equal(isDefaultPersonalProfilePath("C:\\Users\\owner\\AppData\\Local\\Google\\Chrome\\User Data\\Default"),true); assert.equal(isDefaultPersonalProfilePath("/home/owner/.config/google-chrome/Default"),true); const core=new ProviderCore({backend:new FakeBackend(),providerGeneration:1}); await assert.rejects(core.launchProcess({expectedProviderGeneration:1,processGeneration:1,profileMode:"persistent_exclusive",userDataDir:"/home/owner/.config/google-chrome/Default",writableAuthorization:{leaseRef:"lease",fenceRef:"fence"}}),e=>e.code==="personal_profile_forbidden"); });
test("stale context and page generations fail closed", async()=>{const {core,context,page}=await liveTree(); await assert.rejects(core.verifyContext({expectedProviderGeneration:7,contextHandle:context.contextHandle,processGeneration:11,contextGeneration:12}),e=>e.code==="stale_context_generation"); await assert.rejects(core.verifyPageState({expectedProviderGeneration:7,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:16}),e=>e.code==="stale_page_generation");});
test("navigation acknowledgement remains separate from verified readiness",async()=>{const {core,page}=await liveTree(); const d=await core.navigate({expectedProviderGeneration:7,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:17,navigationSequence:1,url:"https://example.test/"}); assert.equal(d.acknowledged,true); assert.equal(d.completionVerified,false); assert.equal(d.state,"committed"); assert.equal(d.evidence.headers.authorization,"[REDACTED]"); const v=await core.verifyPageState({expectedProviderGeneration:7,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:17}); assert.equal(v.verified,true); assert.equal(v.state,"load_complete");});
test("client detach does not terminate Browser Process",async()=>{const {backend,core,process}=await liveTree(); const r=await core.detachProcess({expectedProviderGeneration:7,processHandle:process.processHandle,processGeneration:11}); assert.equal(r.detached,true); assert.equal(r.backendProcessClosed,false); assert.equal(backend.closed,0);});
test("challenge observation has no solve/bypass command",async()=>{const {core}=await liveTree(); const c=core.observeChallenge({expectedProviderGeneration:7,state:"captcha_or_anti_bot",humanCompletionAllowed:true}); assert.equal(c.automationPauseRequired,true); assert.equal(c.bypassAuthorized,false); await assert.rejects(core.handleCommand({operation:"solveChallenge",args:{}}),e=>e.code==="command_not_supported");});
test("download streaming is bounded and cannot claim A07 identity",async()=>{const {core}=await liveTree(); const c=await core.readDownloadChunk({expectedProviderGeneration:7,downloadHandle:"download-1",offset:0,maxBytes:4}); assert.equal(c.bytes.toString(),"abcd"); assert.equal(c.eof,false); assert.equal(c.canonicalContentRef,null); assert.equal(c.canonicalObjectRef,null); await assert.rejects(core.readDownloadChunk({expectedProviderGeneration:7,downloadHandle:"download-1",offset:0,maxBytes:5}),e=>e.code==="download_chunk_too_large");});
test("evidence metadata redacts credential-bearing headers",async()=>{const {core,page}=await liveTree(); const e=await core.captureEvidence({expectedProviderGeneration:7,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:17,evidenceClass:"visible_state"}); assert.equal(e.metadata.headers.cookie,"[REDACTED]"); assert.equal(e.metadata.headers.accept,"application/json"); assert.equal(e.canonicalObjectRef,null);});
test("redaction recursively fences sensitive header values",()=>{const r=redactEvidence({headers:{Authorization:"Bearer secret",Accept:"text/plain"},nested:{cookie:"secret"}}); assert.equal(r.headers.Authorization,"[REDACTED]"); assert.equal(r.headers.Accept,"text/plain"); assert.equal(r.nested.cookie,"[REDACTED]");});
test("provider generation fences every live handle operation",async()=>{const {core,context,page}=await liveTree(); await assert.rejects(core.verifyContext({expectedProviderGeneration:8,contextHandle:context.contextHandle,processGeneration:11,contextGeneration:13}),e=>e.code==="stale_provider_generation"); await assert.rejects(core.captureEvidence({expectedProviderGeneration:8,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:17,evidenceClass:"visible_state"}),e=>e.code==="stale_provider_generation");});
test("detach and reconnect preserve the same live process handle",async()=>{const {core,process}=await liveTree(); await core.detachProcess({expectedProviderGeneration:7,processHandle:process.processHandle,processGeneration:11}); const r=await core.reconnectProcess({expectedProviderGeneration:7,processHandle:process.processHandle,processGeneration:11}); assert.equal(r.reconnected,true); assert.equal(r.processHandle,process.processHandle);});
test("raw credentials are rejected at the provider protocol boundary",async()=>{const core=new ProviderCore({backend:new FakeBackend(),providerGeneration:1}); await assert.rejects(core.handleCommand({operation:"launchProcess",args:{expectedProviderGeneration:1,processGeneration:1,profileMode:"ephemeral",launchOptions:{proxy:{password:"secret"}}}}),e=>e.code==="raw_secret_forbidden");});
test("privacy filtering redacts URL credentials and sensitive query values",()=>{const r=redactUrl("https://alice:secret@example.test/path?token=abc&ok=1"); assert.equal(r.includes("secret"),false); assert.equal(r.includes("token=abc"),false); assert.equal(r.includes("ok=1"),true);});
test("upload integration accepts only A08-materialized path aliases and never claims object identity",async()=>{const {core,page}=await liveTree(); const u=await core.uploadFiles({expectedProviderGeneration:7,pageHandle:page.pageHandle,processGeneration:11,contextGeneration:13,pageGeneration:17,selector:"input[type=file]",materializedPathAliases:["/tmp/a08-materialized-upload.bin"]}); assert.equal(u.acknowledged,true); assert.equal(u.completionVerified,false); assert.deepEqual(u.canonicalObjectRefs,[]);});
